
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/mybatis__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul"
    username: "test"
    password: "test1234!@#$"