server:
  port: 8080
spring:
  profiles:
    active: ${activeProfile:dev}
  devtools:
    livereload:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driverClassName: "net.sf.log4jdbc.sql.jdbcapi.DriverSpy"
    url: "jdbc:log4jdbc:mysql://127.0.0.1:3306/mybatis__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul"
    username: "test"
    password: "test1234!@#$"
mybatis:
  mapper-locations: "mapper/**.xml"
  config-location: "classpath:mybatis-config.xml"

logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF # JDBC 트러블슈팅 경우를 제외하고는 사용 권장 X
      resultset: OFF # ResultSet을 포함한 모든 JDBC 호출 정보를 출력
      resultsettable: OFF  #SQL 결과 데이터 Table형식으로 출력
      sqlonly: INFO     #SQL만 로그만 출력
      sqltiming: OFF    #SQL + 소요시간 출력
      connection : OFF  # 커넥션 연결/종료 정보 출력

